config/routes.rb
#coding:utf-8
Inono::Application.routes.draw do
  # root :to => 'categories#index'
  root :to => "home#index"
  match '/home/index', :to => "home#index"
  match '/simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  resources :customizations, :only => [:index, :show]
  resources :inquiries, :only => [:index, :create]
  resources :measurements
  resources :measure_pages
  resources :links, :only => [:new, :create]
  resources :feedbacks, :only => :create
  resources :events, :only => [:index, :new, :create]
  resources :helps, :only => :show
  resources :notices, :only => :show
  resources :users, :except => [:index, :destroy] do
    member {
      get :ba
      post :create_ruler
    }
  end
  resources :profiles, :only => [:update]
  resources :measures
  resources :orders
  resources :categories do
    collection {
      post :reserve_ruler
      post :reserve_shop
    }
  end
  resources :products do
    resources :comments
    member {
      get :reserve
    }
  end
  resource :session
  resources :blog_posts, :path=>"zhishitang", :only=>[:index,:show]
  resources :blog_comments, :only=>[:create]
  resources :customers
  
  match '/customers/:action', :controller => "customers"

  match '/cart/:action' => 'cart#index'
  match '/customization_wrap/:action' => 'customization_wrap#index'
  match '/change_password' => 'users#change_password', :as => :change_password
  match '/register' => 'users#new', :as => :register
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  namespace :kadmin do
    root :to => 'orders#index'
    resources :customizations
    resources :links, :only => [:index, :edit, :update, :destroy]
    resources :comments do
      resources :replies
    end
    resources :products do
      resources :photos
      collection  {
        get :select_with_ajax
      }
    end
    resources :uploaded_photos
    resources :categories do
      resources :subcategories
    end
    resources :users do
      resources :measures
    end
    resources :orders
    resources :notices
    resources :helps
    resources :feedbacks
    resources :events
    resources :banners
    resources :inquiries
    resources :measure_pages
    resources :measure_properties
    resources :places
    resources :shops
    resources :reserve_rulers , :only=>[:index,:show,:destroy]
    resources :top_rulers , :only=>[:index,:create,:destroy]
    resources :blog_categories
    resources :blog_tags
    resources :blog_posts
    resources :blog_comments
    resources :chats do
      collection {
        get :check
      }
    end
    resources :customers
  end

  # SHIT!!! 谁TMD设计的这个路由.
  match ':category' => 'categories#show'
  match ':category/:subcategory' => 'subcategories#show'

  match '/simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha

  #  match '/:controller(/:action(/:id))'
end

app/controllers/kadmin/banners_controller.rb
#coding:utf-8
class Kadmin::BannersController < KadminController
  def index
    @banners = Banner.paginate :page => params[:page],
      :per_page => 30, :order => 'popularity DESC, created_at DESC'

    respond_to do |format|
      format.html
    end
  end

  def show
    @banner = Banner.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @banner = Banner.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @banner = Banner.find(params[:id])
  end

  def create
    if params[:photo]
      params[:banner][:photo_url] = Photo.save_photo(params[:photo])
    end
    @banner = Banner.new(params[:banner])

    respond_to do |format|
      if @banner.save
        flash[:notice] = 'Banner已经保存.'
        format.html { redirect_to([:kadmin, @banner]) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    if params[:photo]
      params[:banner][:photo_url] = Photo.save_photo(params[:photo])
    end
    @banner = Banner.find(params[:id])

    respond_to do |format|
      if @banner.update_attributes(params[:banner])
        flash[:notice] = 'Banner已更新.'
        format.html { redirect_to([:kadmin, @banner]) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @banner = Banner.find(params[:id])
    Photo.delete(@banner.photo_url)
    @banner.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_banners_url) }
    end
  end
end

app/controllers/kadmin/blog_categories_controller.rb
#coding:utf-8
class Kadmin::BlogCategoriesController < ApplicationController
  layout "kadmin"
  
  def index
    @blog_categories = BlogCategory.all
  end
  
  def show
    @blog_category = BlogCategory.find(params[:id])
  end

  def new
    @blog_category = BlogCategory.new
  end

  def edit
    @blog_category = BlogCategory.find(params[:id])
  end

  def create
    @blog_category = BlogCategory.new(params[:blog_category])

    if @blog_category.save
      redirect_to([:kadmin,@blog_category], :notice => '创建成功.') 
    else
      render :action => "new" 
    end
  end
  
  def update
    @blog_category = BlogCategory.find(params[:id])

    if @blog_category.update_attributes(params[:blog_category])
      redirect_to([:kadmin,@blog_category], :notice => '更新成功.')
    else
      format.html { render :action => "edit" }
    end
  end

  def destroy
    @blog_category = BlogCategory.find(params[:id])
    @blog_category.destroy

    redirect_to(kadmin_blog_categories_url)
  end
end

app/controllers/kadmin/blog_comments_controller.rb
#coding:utf-8
class Kadmin::BlogCommentsController < ApplicationController
  layout "kadmin"
  
  def index
    @blog_comments = BlogComment.all
  end

  def show
    @blog_comment = BlogComment.find(params[:id])
    @blog_post = @blog_comment.blog_post
    @user = @blog_comment.user
  end

  def new
    @blog_comment = BlogComment.new
  end

  def edit
    @blog_comment = BlogComment.find(params[:id])
  end

  def create
    @blog_comment = BlogComment.new(params[:blog_comment])
    if @blog_comment.save
      redirect_to([:kadmin,@blog_comment], :notice => '创建成功.')
    else
      render :action => "new" 
    end
  end
  
  def update
    @blog_comment = BlogComment.find(params[:id])

    if @blog_comment.update_attributes(params[:blog_comment])
      redirect_to([:kadmin,@blog_comment], :notice => '更新成功.')
    else
      render :action => "edit" 
    end
  end

  def destroy
    @blog_comment = BlogComment.find(params[:id])
    @blog_comment.destroy

    redirect_to(kadmin_blog_comments_url)
  end
      
end

app/controllers/kadmin/blog_posts_controller.rb
#coding:utf-8
class Kadmin::BlogPostsController < ApplicationController
  layout 'kadmin'

  def index
    @blog_posts = BlogPost.order("created_at DESC")
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def create
    @blog_post = BlogPost.new(params[:blog_post].merge(:user_id=>current_user.id))
    if @blog_post.save
      redirect_to kadmin_blog_posts_path, :notice => '创建成功.'
    else
      render :action => "new"
    end
  end

  def update
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.update_attributes(params[:blog_post])
      redirect_to kadmin_blog_posts_path, :notice => '更新成功.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    redirect_to(kadmin_blog_posts_url)
  end
end

app/controllers/kadmin/categories_controller.rb
#coding:utf-8
class Kadmin::CategoriesController < KadminController
  def index
    @categories = Category.find(:all, :order => 'popularity DESC')

    @title = '大分类管理-'
    respond_to do |format|
      format.html
      format.xml  { render :xml => @categories }
    end
  end

  def show
    @category = Category.find(params[:id])

    @title = '分类:' + @category.name + '-'
    respond_to do |format|
      format.html
      format.xml  { render :xml => @category }
    end
  end

  def new
    @category = Category.new

    @title = '新分类-'
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @category }
    end
  end

  def edit
    @category = Category.find(params[:id])
    @title = '修改分类-'
  end

  def create
    if params[:category][:logo].empty? and params[:category][:image]
      params[:category][:logo] = Photo.save_photo(params[:category][:image])
      params[:category][:image] = nil
    end
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        flash[:notice] = '分类成功添加.'
        format.html { redirect_to(kadmin_categories_url) }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        flash[:notice] = '分类已修改成功.'
        format.html { redirect_to(kadmin_categories_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/kadmin/chats_controller.rb
class Kadmin::ChatsController < KadminController
  layout "kadmin"

  def index
    @chats = Chat.all
  end

  def check
    if Chat.exists?(:viewed=>nil)
      items = Chat.where(:viewed=>nil).collect { |c| { href: "http://chat.365weiyi.com/chat/#{Tiny::tiny(c.id)}?fr=admin" } }
      render :json => { status: 'ok',items: items }
    else
      render :nothing => true
    end
  end

end

app/controllers/kadmin/comments_controller.rb
#coding:utf-8
class Kadmin::CommentsController < KadminController
  def index
    condition = {:page => params[:page], :per_page => 30, :order => 'created_at DESC, product_id DESC'}
    if params[:product_id]
      condition[:conditions] = ['product_id = ?', params[:product_id]]
    end

    @comments = Comment.paginate(condition)

    respond_to do |format|
      format.html
    end
  end

  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.xml  { render :xml => @comment }
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        flash[:notice] = 'Kadmin::Comment was successfully created.'
        format.html { redirect_to(@comment) }
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.approved = params[:comment][:approved]
    @comment.popularity = params[:comment][:popularity]

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        flash[:notice] = '评论修改成功'
        format.html { redirect_to([:kadmin, @comment]) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_comments_url) }
    end
  end

end

app/controllers/kadmin/companies_controller.rb
#coding:utf-8
class Kadmin::CompaniesController < KadminController
  before_filter :get_role, :only => 'edit'
  def index
    @companies = User.paginate :page => params[:page],
      :per_page => 20, :order => 'created_at DESC, credit DESC',
      :conditions => ['is_company = ?', true]

      respond_to do |format|
        format.html 
      end
  end

  def show
    @company = User.find(params[:id])
    @orders = @company.orders
    @measures = @company.measures

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @user }
    end
  end

  def edit
    @company = User.find(params[:id])
  end

  def update
    @company = User.find(params[:id])
    @company.role = params[:user][:role]

    respond_to do |format|
      if (@company.update_attributes(params[:user]))

        flash[:notice] = '用户修改成功.'
        format.html { redirect_to(kadmin_companies_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @company = User.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_companies_url) }
      format.xml  { head :ok }
    end
  end

private
  def get_role
    @role = [['受限用户', User::BLOCKED], ['普通', User::USER], 
      ['工作人员', User::EDITOR], ['管理员', User::ROOT]]
  end
  
end

app/controllers/kadmin/customers_controller.rb
class Kadmin::CustomersController < ApplicationController
  layout 'kadmin'
  # GET /customers
  # GET /customers.xml
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.xml
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.xml
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.xml
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to([:kadmin,@customer], :notice => 'Customer was successfully created.') }
        format.xml  { render :xml => @customer, :status => :created, :location => @customer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.xml
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to([:kadmin,@customer], :notice => 'Customer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.xml
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_customers_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/kadmin/customizations_controller.rb
#coding:utf-8
class Kadmin::CustomizationsController < KadminController
  before_filter :prepare_category_select, :only => [:new, :edit]

  def index
    @customizations = Customization.paginate :page => params[:page], 
      :per_page => 20,
      :order => 'popularity DESC, updated_at DESC'

    respond_to do |format|
      format.html
    end
  end

  def new
    @customization = Customization.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @customization = Customization.find(params[:id])
  end

  def create
    @customization = Customization.new(params[:customization])

    respond_to do |format|
      if @customization.save
        flash[:notice] = '新闻添加成功.'
        format.html { redirect_to(kadmin_customization_url) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @customization = Customization.find(params[:id])

    respond_to do |format|
      if @customization.update_attributes(params[:customization])
        flash[:notice] = '修改成功.'
        format.html { redirect_to(kadmin_customizations_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @customization = Customization.find(params[:id])
    @customization.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_customizations_url) }
    end
  end

private
  def prepare_category_select
    @customization_category = [["领型"], ["袖口"]]
  end
end

app/controllers/kadmin/events_controller.rb
#coding:utf-8
class Kadmin::EventsController < KadminController
  def index
    @events = Event.paginate :page => params[:page],
      :per_page => 40, :order => 'created_at DESC, price DESC'

    respond_to do |format|
      format.html 
    end
  end

  def show
    redirect_to :action => 'index'
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_events_url) }
    end
  end
end

app/views/kadmin/users/edit.html.erb
<h1>修改用户信息</h1>
<%= link_to '[用户列表]', kadmin_users_path %>
<%= form_for [:kadmin, @user] , :html => { :multipart => true }  do |f| %>
  <%= error_messages_for @user %>
  <p>
    <label>头像:</label>
    <%= f.file_field :avatar %>
    <%= image_tag @user.avatar_medium %>
  </p>
  <p>
    <%= f.label :email, 'Email: ' %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :discount, '享受折扣: ' %>
    <%= f.text_field :discount %> (&lt; 1.0)
  </p>
  <p>
    <%= f.label :credit, '积分: ' %>
    <%= f.text_field :credit, :size => 5 %>
  </p>
  <p>
    <%= f.label :role, '权限: ' %>
    <%= f.select :role, roles %>
  </p>
  <p>
    <%= f.label :is_company, '企业用户' %>
    <%= f.check_box :is_company %>
  </p>
  <p>
    <label>姓名:</label>
    <%= text_field_tag "profile[name]" , @profile.name %>
  </p>  
  <p>
    <label>QQ:</label>
    <%= text_field_tag "profile[qq]"  , @profile.qq %>
  </p>
  <p>
    <label>手机号:</label>
    <%= text_field_tag "profile[phone]" , @profile.phone %>
  </p>
  <p>
    <label>微博:</label>
    <%= text_field_tag "profile[weibo]" , @profile.weibo %>
  </p>
  <p>
    <%= f.submit '确认修改' %>
  </p>
<% end %>

app/views/kadmin/users/index.html.erb
<h1>所有用户</h1>

<%= link_to '[新用户]', new_user_path %>

<% form_tag '/kadmin/users', :method => 'get' do %>
 Email: <%= text_field_tag :email %>
  <%= submit_tag '查询' %>
<% end %>

<table>
  <tr class="tbCaption">
    <th>Email</th>
    <th>昵称</th>
    <th>积分</th>
    <th>折扣</th>
    <th>权限</th>
    <th>订单数</th>
    <th>企业用户</th>
    <th>注册时间</th>
    <th>管理</td>
  </tr>

<% @users.each do |user| %>
  <% profile = user.profile %>
  <tr class="<%= cycle('odd', 'even') %>">
    <td><%=link_to(h(user.email), [:kadmin, user]) %></td>
    <td><%= (profile.blank?)? '' : h(profile.name) %></td>
    <td><%= user.credit %></td>
    <td><%= user.discount %></td>
    <td><%= user.human_role %></td>
    <td><%= link_to(h(user.orders.count.to_s + '单'),
                    kadmin_orders_path(:user_id => user)) %></td>
    <td>
      <% if user.is_company %>
        <%= image_tag('admin/true_small.png') %>
      <% end %>
    </td>
    <td><%= show_time user.created_at %></td>
    <td><%= link_to '[修改]', edit_kadmin_user_path(user) %></td>
    <td><%= link_to '[删除]', [:kadmin, user], :confirm => '确定删除?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />

<%= will_paginate @users, :previous_label => '< ', :next_label => ' >' %>

app/views/kadmin/users/new.html.erb
<h1>New user</h1>

<% form_for(@user) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :real_name %><br />
    <%= f.text_field :real_name %>
  </p>
  <p>
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </p>
  <p>
    <%= f.label :credit %><br />
    <%= f.text_field :credit %>
  </p>
  <p>
    <%= f.label :role %><br />
    <%= f.text_field :role %>
  </p>
  <p>
    <%= f.label :company_id %><br />
    <%= f.text_field :company_id %>
  </p>
  <p>
    <%= f.label :orders_count %><br />
    <%= f.text_field :orders_count %>
  </p>
  <p>
    <%= f.label :is_company %><br />
    <%= f.check_box :is_company %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>

app/views/kadmin/users/show.html.erb
<p>
  <% if @user.is_company %>
    <b>** 公司用户 **</b>
  <% else %>
    <b>** 个人用户 **</b>
  <% end %>
</p>

<%= link_to '[修改信息]', edit_kadmin_user_path(@user) %> |
<%= link_to '[用户列表]', kadmin_users_path %>

<p>
  <b>Email: </b>
  <%=h @user.email %>
</p>

<p>
  <b>积分: </b>
  <%=h @user.credit %>
</p>

<p>
  <b>网站权限: </b>
  <%= @user.human_role %>
</p>
<p>
  <b>注册时间: </b>
  <%= show_time @user.created_at %>
</p>


<% unless @profile.blank? %>
  <p>
    <b>昵称: </b>
    <%=h(@profile.name) %>
  </p>
  <p>
    <b>院校: </b>
    <%=h @profile.institution %>
  </p>

  <p>
    <b>地址: </b>
    <%=h @profile.address %>
    (邮编：<%=h @profile.zipcode %>)
  </p>
  <p>
    <b>网站: </b>
    <%=h @profile.website %>
  </p>
<% end %>

<br />

  <table width="100%" border="0" cellspacing="0" cellpadding="3">
  <tr>
    <td height="30" colspan="7" align="left" bgcolor="#7A7F89" class="fonts">
      <p style="color:white">
      <strong>(共<%= @user.measures.count %>份)身材资料：</strong>
      <%= link_to '[添加身材数据]', new_kadmin_user_measure_path(@user), :style => 'color:white' %> | 
      <%= link_to '[查看所有]', kadmin_user_measures_path(@user), :style => 'color:white' %>
      </p>
    </td>
  </tr>
    <tr>
      <td align="center">数据编号</td>
      <td align="center">描述</td>
      <td align="center">最后更新</td>
      <td align="center">管理</td>
    </tr>

  <% if @measures.empty? %>
    <tr><td><p>您还未量体</p></td></tr>
  <% else %>

    <% @measures.each do |measure| %>

    <tr>
      <td height="40" align="center"><%= measure.id %></td>
      <td align="center"><%=h measure.description %></td>
      <td align="center"><%= show_time measure.updated_at %></td>
      <td align="center">
        <%= link_to '[修改]', edit_kadmin_user_measure_path(@user, measure) %>
        <%= link_to '[删除]', kadmin_user_measure_path(@user, measure), 
          :confirm => '删除后数据不可恢复，您确定要删除？', :method => :delete %>
      </td>
    </tr>

  <% end %>
<% end %>

  </table>


  <table width="100%" border="0" cellspacing="0" cellpadding="3">
  <tr>
    <td height="30" colspan="6" align="left" bgcolor="#7A7F89" class="fonts">
      <p style="color:white">
      <strong>(共<%= @user.orders.count %>笔)该用户的订单：</strong>
      <%= link_to '[查看更多]', kadmin_orders_path(:user_id => @user.id), :style => 'color:white' %>
      </p>
    </td>
  </tr>

    <tr>
      <th>状态</th>
      <th>订单号</th>
      <th>商品种类</th>
      <th>总额</th>
      <th>更新时间</th>
      <th>管理</th>
    </tr>

  <% @orders.each do |order| %>
    <tr style="text-align:center">
      <td><%=h order.progress %></td>
      <td><%= link_to order.id, order, :title => '创建于'+ order.created_at.to_s %> </td>
      <td><%=h order.items.count %></td>
      <td><%= (order.total_price * order.discount) %></td>
      <td><%= show_time order.updated_at %></td>
      <td>
        <%= link_to '[查看]', [:kadmin, order] %>
        <%= link_to '[修改]', edit_kadmin_order_path(order) %>
        <%= link_to '[删除]', [:kadmin, order], :confirm => '确定删除?',
          :method => :delete %>
      </td>
    </tr>
  <% end %>


  </table>