config/routes.rb
#coding:utf-8
Inono::Application.routes.draw do
  # root :to => 'categories#index'
  root :to => "home#index"
  match '/home/index', :to => "home#index"
  match '/simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  resources :customizations, :only => [:index, :show]
  resources :inquiries, :only => [:index, :create]
  resources :measurements
  resources :measure_pages
  resources :links, :only => [:new, :create]
  resources :feedbacks, :only => :create
  resources :events, :only => [:index, :new, :create]
  resources :helps, :only => :show
  resources :notices, :only => :show
  resources :users, :except => [:index, :destroy] do
    member {
      get :ba
      post :create_ruler
    }
  end
  resources :profiles, :only => [:update]
  resources :measures
  resources :orders
  resources :categories do
    collection {
      post :reserve_ruler
      post :reserve_shop
    }
  end
  resources :products do
    resources :comments
    member {
      get :reserve
    }
  end
  resource :session
  resources :blog_posts, :path=>"zhishitang", :only=>[:index,:show]
  resources :blog_comments, :only=>[:create]
  resources :customers
  
  match '/customers/:action', :controller => "customers"

  match '/cart/:action' => 'cart#index'
  match '/customization_wrap/:action' => 'customization_wrap#index'
  match '/change_password' => 'users#change_password', :as => :change_password
  match '/register' => 'users#new', :as => :register
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  namespace :kadmin do
    root :to => 'orders#index'
    resources :customizations
    resources :links, :only => [:index, :edit, :update, :destroy]
    resources :comments do
      resources :replies
    end
    resources :products do
      resources :photos
      collection  {
        get :select_with_ajax
      }
    end
    resources :uploaded_photos
    resources :categories do
      resources :subcategories
    end
    resources :users do
      resources :measures
    end
    resources :orders
    resources :notices
    resources :helps
    resources :feedbacks
    resources :events
    resources :banners
    resources :inquiries
    resources :measure_pages
    resources :measure_properties
    resources :places
    resources :shops
    resources :reserve_rulers , :only=>[:index,:show,:destroy]
    resources :top_rulers , :only=>[:index,:create,:destroy]
    resources :blog_categories
    resources :blog_tags
    resources :blog_posts
    resources :blog_comments
    resources :chats do
      collection {
        get :check
      }
    end
    resources :customers
  end

  # SHIT!!! 谁TMD设计的这个路由.
  match ':category' => 'categories#show'
  match ':category/:subcategory' => 'subcategories#show'

  match '/simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha

  #  match '/:controller(/:action(/:id))'
end

app/controllers/kadmin/banners_controller.rb
#coding:utf-8
class Kadmin::BannersController < KadminController
  def index
    @banners = Banner.paginate :page => params[:page],
      :per_page => 30, :order => 'popularity DESC, created_at DESC'

    respond_to do |format|
      format.html
    end
  end

  def show
    @banner = Banner.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @banner = Banner.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @banner = Banner.find(params[:id])
  end

  def create
    if params[:photo]
      params[:banner][:photo_url] = Photo.save_photo(params[:photo])
    end
    @banner = Banner.new(params[:banner])

    respond_to do |format|
      if @banner.save
        flash[:notice] = 'Banner已经保存.'
        format.html { redirect_to([:kadmin, @banner]) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    if params[:photo]
      params[:banner][:photo_url] = Photo.save_photo(params[:photo])
    end
    @banner = Banner.find(params[:id])

    respond_to do |format|
      if @banner.update_attributes(params[:banner])
        flash[:notice] = 'Banner已更新.'
        format.html { redirect_to([:kadmin, @banner]) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @banner = Banner.find(params[:id])
    Photo.delete(@banner.photo_url)
    @banner.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_banners_url) }
    end
  end
end

app/controllers/kadmin/blog_categories_controller.rb
#coding:utf-8
class Kadmin::BlogCategoriesController < ApplicationController
  layout "kadmin"
  
  def index
    @blog_categories = BlogCategory.all
  end
  
  def show
    @blog_category = BlogCategory.find(params[:id])
  end

  def new
    @blog_category = BlogCategory.new
  end

  def edit
    @blog_category = BlogCategory.find(params[:id])
  end

  def create
    @blog_category = BlogCategory.new(params[:blog_category])

    if @blog_category.save
      redirect_to([:kadmin,@blog_category], :notice => '创建成功.') 
    else
      render :action => "new" 
    end
  end
  
  def update
    @blog_category = BlogCategory.find(params[:id])

    if @blog_category.update_attributes(params[:blog_category])
      redirect_to([:kadmin,@blog_category], :notice => '更新成功.')
    else
      format.html { render :action => "edit" }
    end
  end

  def destroy
    @blog_category = BlogCategory.find(params[:id])
    @blog_category.destroy

    redirect_to(kadmin_blog_categories_url)
  end
end

app/controllers/kadmin/blog_comments_controller.rb
#coding:utf-8
class Kadmin::BlogCommentsController < ApplicationController
  layout "kadmin"
  
  def index
    @blog_comments = BlogComment.all
  end

  def show
    @blog_comment = BlogComment.find(params[:id])
    @blog_post = @blog_comment.blog_post
    @user = @blog_comment.user
  end

  def new
    @blog_comment = BlogComment.new
  end

  def edit
    @blog_comment = BlogComment.find(params[:id])
  end

  def create
    @blog_comment = BlogComment.new(params[:blog_comment])
    if @blog_comment.save
      redirect_to([:kadmin,@blog_comment], :notice => '创建成功.')
    else
      render :action => "new" 
    end
  end
  
  def update
    @blog_comment = BlogComment.find(params[:id])

    if @blog_comment.update_attributes(params[:blog_comment])
      redirect_to([:kadmin,@blog_comment], :notice => '更新成功.')
    else
      render :action => "edit" 
    end
  end

  def destroy
    @blog_comment = BlogComment.find(params[:id])
    @blog_comment.destroy

    redirect_to(kadmin_blog_comments_url)
  end
      
end

app/controllers/kadmin/blog_posts_controller.rb
#coding:utf-8
class Kadmin::BlogPostsController < ApplicationController
  layout 'kadmin'

  def index
    @blog_posts = BlogPost.order("created_at DESC")
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def create
    @blog_post = BlogPost.new(params[:blog_post].merge(:user_id=>current_user.id))
    if @blog_post.save
      redirect_to kadmin_blog_posts_path, :notice => '创建成功.'
    else
      render :action => "new"
    end
  end

  def update
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.update_attributes(params[:blog_post])
      redirect_to kadmin_blog_posts_path, :notice => '更新成功.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    redirect_to(kadmin_blog_posts_url)
  end
end

app/controllers/kadmin/categories_controller.rb
#coding:utf-8
class Kadmin::CategoriesController < KadminController
  def index
    @categories = Category.find(:all, :order => 'popularity DESC')

    @title = '大分类管理-'
    respond_to do |format|
      format.html
      format.xml  { render :xml => @categories }
    end
  end

  def show
    @category = Category.find(params[:id])

    @title = '分类:' + @category.name + '-'
    respond_to do |format|
      format.html
      format.xml  { render :xml => @category }
    end
  end

  def new
    @category = Category.new

    @title = '新分类-'
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @category }
    end
  end

  def edit
    @category = Category.find(params[:id])
    @title = '修改分类-'
  end

  def create
    if params[:category][:logo].empty? and params[:category][:image]
      params[:category][:logo] = Photo.save_photo(params[:category][:image])
      params[:category][:image] = nil
    end
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        flash[:notice] = '分类成功添加.'
        format.html { redirect_to(kadmin_categories_url) }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        flash[:notice] = '分类已修改成功.'
        format.html { redirect_to(kadmin_categories_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/kadmin/chats_controller.rb
class Kadmin::ChatsController < KadminController
  layout "kadmin"

  def index
    @chats = Chat.all
  end

  def check
    if Chat.exists?(:viewed=>nil)
      items = Chat.where(:viewed=>nil).collect { |c| { href: "http://chat.365weiyi.com/chat/#{Tiny::tiny(c.id)}?fr=admin" } }
      render :json => { status: 'ok',items: items }
    else
      render :nothing => true
    end
  end

end

app/controllers/kadmin/comments_controller.rb
#coding:utf-8
class Kadmin::CommentsController < KadminController
  def index
    condition = {:page => params[:page], :per_page => 30, :order => 'created_at DESC, product_id DESC'}
    if params[:product_id]
      condition[:conditions] = ['product_id = ?', params[:product_id]]
    end

    @comments = Comment.paginate(condition)

    respond_to do |format|
      format.html
    end
  end

  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.xml  { render :xml => @comment }
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        flash[:notice] = 'Kadmin::Comment was successfully created.'
        format.html { redirect_to(@comment) }
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.approved = params[:comment][:approved]
    @comment.popularity = params[:comment][:popularity]

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        flash[:notice] = '评论修改成功'
        format.html { redirect_to([:kadmin, @comment]) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_comments_url) }
    end
  end

end

app/controllers/kadmin/companies_controller.rb
#coding:utf-8
class Kadmin::CompaniesController < KadminController
  before_filter :get_role, :only => 'edit'
  def index
    @companies = User.paginate :page => params[:page],
      :per_page => 20, :order => 'created_at DESC, credit DESC',
      :conditions => ['is_company = ?', true]

      respond_to do |format|
        format.html 
      end
  end

  def show
    @company = User.find(params[:id])
    @orders = @company.orders
    @measures = @company.measures

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @user }
    end
  end

  def edit
    @company = User.find(params[:id])
  end

  def update
    @company = User.find(params[:id])
    @company.role = params[:user][:role]

    respond_to do |format|
      if (@company.update_attributes(params[:user]))

        flash[:notice] = '用户修改成功.'
        format.html { redirect_to(kadmin_companies_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @company = User.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_companies_url) }
      format.xml  { head :ok }
    end
  end

private
  def get_role
    @role = [['受限用户', User::BLOCKED], ['普通', User::USER], 
      ['工作人员', User::EDITOR], ['管理员', User::ROOT]]
  end
  
end

app/controllers/kadmin/customers_controller.rb
class Kadmin::CustomersController < ApplicationController
  layout 'kadmin'
  # GET /customers
  # GET /customers.xml
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.xml
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.xml
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.xml
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to([:kadmin,@customer], :notice => 'Customer was successfully created.') }
        format.xml  { render :xml => @customer, :status => :created, :location => @customer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.xml
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to([:kadmin,@customer], :notice => 'Customer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.xml
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_customers_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/kadmin/customizations_controller.rb
#coding:utf-8
class Kadmin::CustomizationsController < KadminController
  before_filter :prepare_category_select, :only => [:new, :edit]

  def index
    @customizations = Customization.paginate :page => params[:page], 
      :per_page => 20,
      :order => 'popularity DESC, updated_at DESC'

    respond_to do |format|
      format.html
    end
  end

  def new
    @customization = Customization.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @customization = Customization.find(params[:id])
  end

  def create
    @customization = Customization.new(params[:customization])

    respond_to do |format|
      if @customization.save
        flash[:notice] = '新闻添加成功.'
        format.html { redirect_to(kadmin_customization_url) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @customization = Customization.find(params[:id])

    respond_to do |format|
      if @customization.update_attributes(params[:customization])
        flash[:notice] = '修改成功.'
        format.html { redirect_to(kadmin_customizations_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @customization = Customization.find(params[:id])
    @customization.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_customizations_url) }
    end
  end

private
  def prepare_category_select
    @customization_category = [["领型"], ["袖口"]]
  end
end

app/controllers/kadmin/events_controller.rb
#coding:utf-8
class Kadmin::EventsController < KadminController
  def index
    @events = Event.paginate :page => params[:page],
      :per_page => 40, :order => 'created_at DESC, price DESC'

    respond_to do |format|
      format.html 
    end
  end

  def show
    redirect_to :action => 'index'
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(kadmin_events_url) }
    end
  end
end

app/views/kadmin/orders/edit.html.erb
<h1>修改订单</h1>
<br />
<%= link_to '[订单列表]', kadmin_orders_path %>
<%= link_to '[查看本订单]', [:kadmin, @order] %>
<br /><br />

<% form_for([:kadmin, @order]) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :progress, '订单状态：' %>
    <%= f.select :progress, @progress %>
  </p>
  <p>
    <%= f.label :name, '收货人：' %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :address, '收货地址：' %>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :zipcode, '邮编：' %>
    <%= f.text_field :zipcode %>
  </p>
  <p>
    <%= f.label :phone, '联系电话：' %>
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :extra_information, '备 注：' %> (其它联系方式，特别说明等)<br />
    <%= f.text_area :extra_information, :size => '30x4' %>
  </p>
  <p>
    <%= f.label :appointment, '量体时间：' %><br />
    <%= f.text_area :appointment, :size => '30x5' %>
  </p>
  <br />
  <p>
    <%= f.submit '确认修改' %>
  </p>
<% end %>

<br />
<hr />
<h1>购物单详情</h1>
<br />

<table>

<tr>
  <td>订单总价：<%= @items.sum {|i| i.total_price} %></td>
</tr>

<tr>
  <td>商品</td>
  <td>单价</td>
  <td>数量</td>
  <td>总价</td>
</tr>

<% if @items.empty? %>
  <tr>
    <td>该订单中没有商品</td>
  </tr>
<% else %>

    <% @items.each do |i| %>
    <tr>
      <td><%=h i.product.name %></td>
      <td><%=h i.product.our_price %></td>
      <td><%=h i.quantity %></td>
      <td><%= i.total_price %></td>
    </tr>
    <% end %>

<% end #if else%>
</table>

app/views/kadmin/orders/index.html.erb
<% if current_user.email != "hejun@365weiyi.com" %> 
  <h1>所有订单</h1>

  <% form_tag kadmin_orders_path, :method => :get do %>
    请选择您要查看的订单：<%= select_tag :c, options_for_select(@progress, @order_category), {:default => true} %>
    <%= submit_tag '查看', :name => nil %>
  <% end %>


  <table>
    <tr class="tbCaption">
      <th>状态</th>
      <th>订单号</th>
      <th>用户</th>
      <th>商品种类</th>
      <th>送货方式</th>
      <th>支付手段</th>
      <th>原始价</th>
      <th>折扣</th>
      <th>折后价</th>
      <th>管理</th>
    </tr>

    <% @orders.each do |order| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%=h order.progress %></td>
        <td><%= link_to order.id, [:kadmin, order] %></td>
        <td>
          <% user = order.user %>
          <% if user %>
            <%= link_to(h(user.email),
              kadmin_user_path(user), :target => '_blank') %>
          <% end %>
        </td>
        <td><%=h order.items.count %></td>
        <td><%=h order.shipping %></td>
        <td><%=h order.payment %></td>
        <td><%=h order.total_price %></td>
        <td><%= (order.discount * 100).to_s + '%' %></td>
        <td><%= (order.total_price * order.discount) %></td>
        <td><%= link_to '[修改]', edit_kadmin_order_path(order) %></td>
        <td><%= link_to '[删除]', [:kadmin, order], :confirm => '确定删除?', :method => :delete %></td>
      </tr>
    <% end %>

    <tr>
      <td colspan="8"><%= will_paginate @orders, :previous_label => '< ',
          :next_label => ' >' %></td>
    </tr>
  </table>
<% end %>

app/views/kadmin/orders/new.html.erb
<h1>提交订单</h1>
<br />

<% form_for(@order) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :address, '客户地址：' %>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :phone, '联系电话：' %>
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :appointment, '预约量体时间：' %>
    <%= f.text_field :appointment %>
  </p>
  <p>
    <%= f.label :description, '备 注：' %> (其它联系方式，特别说明等)<br />
    <%= f.text_area :description, :size => '40x5' %>
  </p>
  <br />
  <p>
    <%= f.submit '提交订单' %>
  </p>
<% end %>

<hr />
<h1>您的购物单</h1>
<br />

<table>
<tr>
  <td>商品</td>
  <td>单价</td>
  <td>数量</td>
  <td>总价</td>
</tr>

<% if @items.empty? %>
  <tr><p>您的购物车暂时为空</p></tr>
<% else %>

    <% @items.each do |i| %>
    <tr>
      <td><%=h i.name %></td>
      <td><%=h i.product.our_price %></td>
      <td><%=h i.quantity %></td>
      <td><%= i.price %></td>
    </tr>
    <% end %>

<% end #if else%>

  <tr>
    <td>订单总价：<%= @cart.price %></td>
    <td><%= link_to '[返回修改]', :controller => :cart, :action => :edit %></td>
  </tr>
</table>

app/views/kadmin/orders/show.html.erb
<h1>查看订单</h1>
<br />
<%= link_to '[所有订单]', kadmin_orders_path %>

<p>
订单号：<%=h @order.id %>
</p>
<p>
订单状态：<%=h @order.progress %>
</p>
<p>
下单时间：<%= show_time @order.created_at %>
</p>
<p>
客户地址：<%=h @order.address %>
</p>
<p>
联系电话：<%=h @order.phone %>
</p>
<p>
预约量体时间：<%=h @order.appointment %>
</p>
<p>
备 注：<%=h @order.extra_information %>
</p>
<p>
送货方式：<%=h @order.shipping %>
</p>
<p>
支付手段：<%=h @order.payment %>
</p>
<br />

<hr />
<h1>您的购物单</h1>
<br />

<table>
<tr>
  <td>商品</td>
  <td>尺码</td>
  <td>单价</td>
  <td>数量</td>
  <td>总价</td>
</tr>

<% if @items.empty? %>
  <tr>
    <td>该订单中没有商品</td>
  </tr>
<% else %>

    <% @items.each do |i| %>
    <tr>
      <td><%=h i.product.name %></td>
      <td><%=h i.measure %></td>
      <td><%=h i.product.our_price %></td>
      <td><%=h i.quantity %></td>
      <td><%= i.total_price %></td>
    </tr>
    <% end %>

<% end #if else%>

  <tr>
    <td>订单总价：<%= @items.sum {|i| i.total_price} %></td>
  </tr>
</table>